language: node_js
sudo: required
node_js:
- 7
- 6
before_install:
  - "mv config.example.json config.json"
  - "sudo npm install -g @angular/cli"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script:
- npm test
- npm run coveralls
cache:
  directories:
  - node_modules
