language: node_js
node_js:
- 7
- 6
before_install:
  - "export CHROME_BIN=chromium_browser"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "mv config.example.json config.json"
  - "npm install -g @angular/cli"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script:
- npm test
- npm run coveralls
cache:
  directories:
  - node_modules
notifications:
  email: false
